jsy78/SEMI-PJT-1122

- accounts/static/accounts/css/login.css
- accounts/static/accounts/css/signup.css
- accounts/templates/accounts/login.html
- accounts/templates/accounts/signup.html
- login(로그인) 템플릿 생성
- signup(회원가입) 템플릿 생성
> feat: templates 생성

- accounts/views.py
- accounts/views.py
- 로그인에서 redirection 변경
> fix : 로그인 기능 수정

- accounts/static/accounts/css/login.css
- accounts/static/accounts/css/profile.css
- accounts/templates/accounts/profile.html
> docs: accounts/templates 진행

- cafes/templates/detail.html
feat: 게시글 클릭해서 이동 시 보이는 화면 front-end
>  feat: 게시글 클릭해서 이동 시 보이는 화면 front-end

- accounts/static/accounts/css/profile.css
- accounts/static/accounts/js/profile.js
- accounts/templates/accounts/login.html
- accounts/templates/accounts/profile.html
- accounts/templates/accounts/signup.html
- accounts/urls.py
- accounts/views.py
- signup/login 불필요한 코드 제거
- profile 전반적 비율 수정
- profile 메뉴 구현
> feat: profile template 구현

- accounts/urls.py
- accounts/views.py
- 원래 없애고 올려야 했던 임시 url, views 삭제
> fix: url, views 수정

- accounts/static/accounts/css/login.css
- accounts/static/accounts/css/signup.css
- accounts/templates/accounts/profile.html
- signup/login 비율 조절
- profile DTL 작성
> docs: templates 수정

- accounts/static/accounts/css/update.css
- accounts/templates/accounts/update.html
> feat: update 템플릿 작성

- accounts/urls.py
- accounts/views.py
- accounts/urls 주석 profile 주석 해제
- accounts/views 로그인, 회원가입 리다이렉션 수정 / 프로필 추가
> fix : 로그인, 회원 가입 리다이렉션 수정 완료

- accounts/static/accounts/css/signup.css
- accounts/templates/accounts/login.html
- accounts/templates/accounts/profile.html
- templates/base.html
- templates/footer.html
- templates/main.html
- templates/navbar.html
navbar, footer 별도 파일로 분리
navbar, footer fixed-top, fixed-bottom 제거
base container style="min-height: 100vh;" 추가
signup css와 navbar css가 겹치는 문제 수정
들여쓰기 수정
> fix : navbar 상단 고정, footer 하단 고정, signup css 수정

- accounts/templates/accounts/login.html
- accounts/templates/accounts/profile.html
- accounts/templates/accounts/signup.html
- 이미지 파일 불러오게 수정
- profile 버튼 if 문 수정
> fix: 사라진 부분 수정

- accounts/static/accounts/css/profile.css
- accounts/templates/accounts/profile.html
> docs: follow/unfollow로 수정

- accounts/static/accounts/css/update.css
- accounts/templates/accounts/profile.html
- accounts/templates/accounts/update.html
- accounts/views.py
- profile html 링크 수정 (임시)
- update 함수 추가
- update html 링크 수정 (임시)
- update template 폼 정리
- update template css 수정
> feat : 프로필  update 기능

- accounts/templates/accounts/update.html
- accounts/views.py
- 회원 가입시 프로필 이미지 DB에 저장되지 않는 오류 해결
- 회원 정보 수정 페이지에 프로필 이미지가 보이지 않는 오류 해결
> fix : 회원 가입 및 회원 정보 수정 오류 해결

- accounts/views.py
> fix : 회원 정보 수정 에러 수정

- cafes/static/cafes/css/cafe_detail.css
- cafes/templates/cafes/cafe_detail.html
- html 정리
- css 생성
- template 수정
> docs: cafe_detail template 수정

- cafes/static/cafes/css/cafe_detail.css
- cafes/templates/cafes/cafe_detail.html
css 별도 파일로 분리
지도 부분 <html></html>이 통째로 들어가있던 부분 수정
들여쓰기 수정
태그가 제대로 닫히지 않은 부분 수정
중복되는 자바스크립트 함수 제거
> style : cafe_detail.html 코드 스타일 정리

- static/css/base.css
- templates/base.html
> docs: 폰트 추가

- static/css/base.css
- static/css/navbar.css
> fix : 사이드바 캐러셀 수정

- accounts/static/accounts/css/profile.css
- accounts/static/accounts/js/profile.js
- accounts/templates/accounts/profile.html
- accounts/views.py
- static/css/navbar.css
- 즐겨찾기한 글, 좋아요한 글 실제 정보를 불러오기 위한 views 수정
- 작성한 글 실제 정보, 링크 추가
- 즐겨찾기한 글 실제 정보, 링크 추가
- 좋아요 한 글 실제 정보, 링크 추가
> docs: 프로필 글 수정

- accounts/templates/accounts/profile.html
- accounts/views.py
> feat : 팔로우 기능 비동기로 처리

- templates/main.html
> style : border none

- accounts/static/accounts/css/profile.css
- accounts/templates/accounts/profile.html
- 작성된/북마크한/좋아요한 글이 없을 경우 더보기 글자가 안 보이게 수정
- 작성된/북마크한/좋아요한 글이 없을 경우 출력되는 문구 생성
> docs: 글이 없을 경우 더보기/문구 출력 수정

- config/views.py
- templates/main.html
> feat : main page cafe list

- templates/main.html
> chore : main page

- templates/footer.html
> feat : footer git 주소 추가

- templates/base.html
> fix : 탑 버튼

- cafes/templates/cafes/cafe_detail.html
- cafes/templates/cafes/reply.html
댓글, 리뷰 좋아요 비동기 오류 수정
코드 스타일 수정
> fix, style : cafe_detail 수정

- cafes/templates/cafes/cafe_search.html
> fix : 검색 카페 목록

- templates/main.html
> feat : 임시로 카페 추가 버튼 메인에 추가

- cafes/static/cafes/css/category.css
- static/css/base.css
- static/css/footer.css
- static/css/navbar.css
- templates/footer.html
- templates/navbar.html
- nav/footer 코드 정리
- footer 수정
> chore: 코드 정리, footer 수정

- cafes/templates/cafes/category.html
- cafes/views.py
- 사이드바 메뉴에서 각각 카테고리 클릭 시 "[클릭한 카테고리] 카페"가 출력되지 않는 부분 해결
> fix : 카테고리 페이지 수정

- cafes/templates/cafes/cafe_detail.html
- cafes/templates/cafes/category.html
fix : cafe_deatail,category 페이지 별점 반올림 구현
> fix : cafe_deatail,category 페이지 별점 반올림 구현

- templates/main.html
> style: main페이지 평점 반올림 적용

- cafes/templates/cafes/cafe_detail.html
cafe_detail 페이지 이 매장이 소개된 테마 이미지 클릭 시 테마별로 연결되도록 수정
> fix : cafe_detail 페이지 이 매장이 소개된 테마 이미지 클릭 시 테마별로 연결되도록 수정

- templates/main.html
> style : 메인 페이지 카페 목록 안내 문구, 새로운 카페 생성 버튼, 카페 자세히 보기 버튼

- templates/main.html
- 제목 변경
- 무한 스크롤 페이지네이션 next 삭제
> fix : 메인 페이지 수정

- cafes/templates/cafes/cafe_detail.html
> feat : 카페 게시글 삭제 기능 추가

- cafes/views.py
- 검색창에 아무것도 입력하지 않을 경우 main 페이지로 리다이렉션
> fix : 검색 기능 수정

- cafes/templates/cafes/cafe_search.html
- templates/main.html
> fix : 무한 스크롤 관련 클래스 추가

- cafes/templates/cafes/cafe_detail.html
> fix : 게시글 삭제 오류 수정

- cafes/templates/cafes/cafe_detail.html
- 게시글 삭제시 CSRF token 검증 실패 에러 수정
> fix : CSRF 검증 에러 수정

- cafes/views.py
- 카페 게시글 삭제시 메인페이지로 리다이렉션하게 변경
> fix : 게시글 삭제 후 리다이렉션 변경
